/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Diego
 */
public class FrmAnalisis_ventas extends javax.swing.JFrame {

    /**
     * Creates new form Gerentedistrital
     */
    public FrmAnalisis_ventas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TBLtienda_enTien = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        LBLnombre_tienda = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        LBLempaques_enTien = new javax.swing.JLabel();
        LBLvasos_enTien = new javax.swing.JLabel();
        LBLbolsas_enTien = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        LBLganancias = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TBLtienda_enTien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(TBLtienda_enTien);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 610, 160));

        jLabel1.setBackground(new java.awt.Color(102, 255, 204));
        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 227, 169));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DATOS DE TIENDA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 130, 20));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\josej\\Documents\\NetBeansProjects\\ADS\\imagenes\\small_icon_starbucks.png")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 10, 90, 80));

        jPanel1.setBackground(new java.awt.Color(255, 93, 93));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 93, 93)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LBLnombre_tienda.setBackground(new java.awt.Color(102, 255, 204));
        LBLnombre_tienda.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        LBLnombre_tienda.setForeground(new java.awt.Color(255, 227, 169));
        LBLnombre_tienda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(LBLnombre_tienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 310, 34));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 330, 70));

        jPanel2.setBackground(new java.awt.Color(255, 93, 93));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LBLempaques_enTien.setBackground(new java.awt.Color(102, 255, 204));
        LBLempaques_enTien.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        LBLempaques_enTien.setForeground(new java.awt.Color(255, 227, 169));
        LBLempaques_enTien.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LBLempaques_enTien.setText("empaques = ");
        jPanel2.add(LBLempaques_enTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 130, 20));

        LBLvasos_enTien.setBackground(new java.awt.Color(102, 255, 204));
        LBLvasos_enTien.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        LBLvasos_enTien.setForeground(new java.awt.Color(255, 227, 169));
        LBLvasos_enTien.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LBLvasos_enTien.setText("vasos = ");
        jPanel2.add(LBLvasos_enTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 150, 20));

        LBLbolsas_enTien.setBackground(new java.awt.Color(102, 255, 204));
        LBLbolsas_enTien.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        LBLbolsas_enTien.setForeground(new java.awt.Color(255, 227, 169));
        LBLbolsas_enTien.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LBLbolsas_enTien.setText("bolsas =");
        jPanel2.add(LBLbolsas_enTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 130, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 180, 200, 200));

        jPanel3.setBackground(new java.awt.Color(255, 93, 93));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LBLganancias.setBackground(new java.awt.Color(102, 255, 204));
        LBLganancias.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        LBLganancias.setForeground(new java.awt.Color(255, 227, 169));
        LBLganancias.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LBLganancias.setText("Ganancias = s/. ");
        jPanel3.add(LBLganancias, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 50));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 240, 70));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\josej\\Documents\\NetBeansProjects\\ADS\\imagenes\\cafeteria.jpg")); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAnalisis_ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAnalisis_ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAnalisis_ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAnalisis_ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAnalisis_ventas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel LBLbolsas_enTien;
    public javax.swing.JLabel LBLempaques_enTien;
    public javax.swing.JLabel LBLganancias;
    public javax.swing.JLabel LBLnombre_tienda;
    public javax.swing.JLabel LBLvasos_enTien;
    public javax.swing.JTable TBLtienda_enTien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
