/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Diego
 */
public class FrmAnalisis_urgencia extends javax.swing.JFrame {

    /**
     * Creates new form Gerentedistrital
     */
    public FrmAnalisis_urgencia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TBLtienda_enDirec = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        CBXurgencia_enDirec = new javax.swing.JComboBox<>();
        BTNconsultar_enDirec = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        LBLganancias_enDirec = new javax.swing.JLabel();
        BTNlimpiar_enDirec = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TBLtienda_enDirec.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(TBLtienda_enDirec);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 1120, 160));

        jLabel1.setBackground(new java.awt.Color(102, 255, 204));
        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 227, 169));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DATOS DE TIENDA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 130, 20));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\josej\\Documents\\NetBeansProjects\\ADS\\imagenes\\small_icon_starbucks.png")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 10, 90, 80));

        jPanel1.setBackground(new java.awt.Color(255, 93, 93));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 93, 93)));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(102, 255, 204));
        jLabel3.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 227, 169));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ordenar por urgencia");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 180, 34));

        CBXurgencia_enDirec.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        CBXurgencia_enDirec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Urgente", "Alta", "Normal", "Bajo" }));
        jPanel1.add(CBXurgencia_enDirec, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 190, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 450, 70));

        BTNconsultar_enDirec.setBackground(new java.awt.Color(255, 93, 93));
        BTNconsultar_enDirec.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        BTNconsultar_enDirec.setForeground(new java.awt.Color(255, 227, 169));
        BTNconsultar_enDirec.setText("CONSULTAR");
        getContentPane().add(BTNconsultar_enDirec, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 420, 260, 70));

        jPanel4.setBackground(new java.awt.Color(255, 93, 93));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LBLganancias_enDirec.setBackground(new java.awt.Color(102, 255, 204));
        LBLganancias_enDirec.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        LBLganancias_enDirec.setForeground(new java.awt.Color(255, 227, 169));
        LBLganancias_enDirec.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LBLganancias_enDirec.setText("Ganancias = s/. ");
        jPanel4.add(LBLganancias_enDirec, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 50));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 240, 70));

        BTNlimpiar_enDirec.setBackground(new java.awt.Color(255, 93, 93));
        BTNlimpiar_enDirec.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        BTNlimpiar_enDirec.setForeground(new java.awt.Color(255, 227, 169));
        BTNlimpiar_enDirec.setText("limpiar");
        getContentPane().add(BTNlimpiar_enDirec, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 420, 260, 70));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\josej\\Documents\\NetBeansProjects\\ADS\\imagenes\\cafeteria.jpg")); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAnalisis_urgencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAnalisis_urgencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAnalisis_urgencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAnalisis_urgencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAnalisis_urgencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BTNconsultar_enDirec;
    public javax.swing.JButton BTNlimpiar_enDirec;
    public javax.swing.JComboBox<String> CBXurgencia_enDirec;
    public javax.swing.JLabel LBLganancias_enDirec;
    public javax.swing.JTable TBLtienda_enDirec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
