package Vista;
import Modelo.PlaceHolder;
public class FrmVentas extends javax.swing.JFrame {

    public FrmVentas() {
        initComponents();
        PlaceHolder phNombrePro = new PlaceHolder("Pedido", TXTnombre_pro);
        PlaceHolder phCantPro = new PlaceHolder("Cantidad", TXTcnt_pro);
        PlaceHolder phPrecioUni = new PlaceHolder("P/U", TXTprecio_unitario);
        
        PlaceHolder phNombreCliente = new PlaceHolder("Nombres", TXTnombre_cliente);
        PlaceHolder phApellCliente = new PlaceHolder("Apellidos", TXTapell_cliente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        BTNregistrar_venta = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        TXTnombre_pro = new javax.swing.JTextField();
        TXTcnt_pro = new javax.swing.JTextField();
        TXTprecio_unitario = new javax.swing.JTextField();
        RBTNvaso = new javax.swing.JRadioButton();
        RBTNbolsa = new javax.swing.JRadioButton();
        RBTNempaque = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        TXTapell_cliente = new javax.swing.JTextField();
        TXTnombre_cliente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        BTNregistrar_pedido = new javax.swing.JButton();
        BTNregistrar_cliente = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CBXtienda_ventas = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 255)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 838, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 338, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BTNregistrar_venta.setBackground(new java.awt.Color(255, 227, 169));
        BTNregistrar_venta.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        BTNregistrar_venta.setForeground(new java.awt.Color(255, 93, 93));
        BTNregistrar_venta.setText("REGISTRAR VENTA");
        getContentPane().add(BTNregistrar_venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 500, 200, 60));

        jPanel3.setBackground(new java.awt.Color(255, 227, 169));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(102, 102, 255));
        jLabel8.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 93, 93));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("DATOS DEL PEDIDO");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 170, 20));

        TXTnombre_pro.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        TXTnombre_pro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTnombre_proActionPerformed(evt);
            }
        });
        jPanel3.add(TXTnombre_pro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 300, 50));

        TXTcnt_pro.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        TXTcnt_pro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTcnt_proActionPerformed(evt);
            }
        });
        jPanel3.add(TXTcnt_pro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 130, 50));

        TXTprecio_unitario.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        TXTprecio_unitario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTprecio_unitarioActionPerformed(evt);
            }
        });
        jPanel3.add(TXTprecio_unitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 130, 50));

        RBTNvaso.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        RBTNvaso.setText("VASO");
        RBTNvaso.setBorder(null);
        RBTNvaso.setOpaque(false);
        RBTNvaso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBTNvasoActionPerformed(evt);
            }
        });
        jPanel3.add(RBTNvaso, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        RBTNbolsa.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        RBTNbolsa.setText("BOLSA");
        RBTNbolsa.setBorder(null);
        RBTNbolsa.setOpaque(false);
        jPanel3.add(RBTNbolsa, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        RBTNempaque.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        RBTNempaque.setText("EMPAQUE");
        RBTNempaque.setBorder(null);
        RBTNempaque.setOpaque(false);
        jPanel3.add(RBTNempaque, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 340, 210));

        jPanel4.setBackground(new java.awt.Color(255, 227, 169));

        TXTapell_cliente.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N

        TXTnombre_cliente.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        TXTnombre_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTnombre_clienteActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(102, 102, 255));
        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 93, 93));
        jLabel1.setText("DATOS DEL CLIENTE");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TXTnombre_cliente, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                    .addComponent(TXTapell_cliente))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(TXTnombre_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TXTapell_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 380, 210));

        BTNregistrar_pedido.setBackground(new java.awt.Color(255, 227, 169));
        BTNregistrar_pedido.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        BTNregistrar_pedido.setForeground(new java.awt.Color(255, 93, 93));
        BTNregistrar_pedido.setText("registrar pedido");
        getContentPane().add(BTNregistrar_pedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 500, 200, 60));

        BTNregistrar_cliente.setBackground(new java.awt.Color(255, 227, 169));
        BTNregistrar_cliente.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        BTNregistrar_cliente.setForeground(new java.awt.Color(255, 93, 93));
        BTNregistrar_cliente.setText("registrar cliente");
        getContentPane().add(BTNregistrar_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 200, 60));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 800, 340));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 220));

        CBXtienda_ventas.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        CBXtienda_ventas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Starbucks Plz. Norte", "Starbucks Mega Plaza", "Starbucks Av. Tomas Valle" }));
        getContentPane().add(CBXtienda_ventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 210, 60));

        jLabel3.setBackground(new java.awt.Color(255, 255, 153));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -20, 830, 260));

        jPanel1.setBackground(new java.awt.Color(255, 255, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 800, 20));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TXTnombre_proActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTnombre_proActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTnombre_proActionPerformed

    private void TXTcnt_proActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTcnt_proActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTcnt_proActionPerformed

    private void TXTprecio_unitarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTprecio_unitarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTprecio_unitarioActionPerformed

    private void TXTnombre_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTnombre_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTnombre_clienteActionPerformed

    private void RBTNvasoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBTNvasoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RBTNvasoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BTNregistrar_cliente;
    public javax.swing.JButton BTNregistrar_pedido;
    public javax.swing.JButton BTNregistrar_venta;
    public javax.swing.JComboBox<String> CBXtienda_ventas;
    public javax.swing.JRadioButton RBTNbolsa;
    public javax.swing.JRadioButton RBTNempaque;
    public javax.swing.JRadioButton RBTNvaso;
    public javax.swing.JTextField TXTapell_cliente;
    public javax.swing.JTextField TXTcnt_pro;
    public javax.swing.JTextField TXTnombre_cliente;
    public javax.swing.JTextField TXTnombre_pro;
    public javax.swing.JTextField TXTprecio_unitario;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
